// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Style", "IDE0044:Add readonly modifier", Justification = "<Pending>", Scope = "member", Target = "~F:BurnSoft.Database.MSSQL.MssqlDatabase.ClassLocation")]
[assembly: SuppressMessage("Style", "IDE0044:Add readonly modifier", Justification = "<Pending>", Scope = "member", Target = "~F:BurnSoft.Database.MySQL.MySqlDatabase.ClassLocation")]
[assembly: SuppressMessage("Style", "IDE0044:Add readonly modifier", Justification = "<Pending>", Scope = "member", Target = "~F:BurnSoft.Database.SQLite.BaseDatabase.ClassLocation")]
[assembly: SuppressMessage("Style", "IDE0044:Add readonly modifier", Justification = "<Pending>", Scope = "member", Target = "~F:BurnSoft.Database.SQLite.SqLiteDataManagement.ClassLocation")]
[assembly: SuppressMessage("Style", "IDE0059:Unnecessary assignment of a value", Justification = "<Pending>", Scope = "member", Target = "~M:BurnSoft.Database.MSSQL.MssqlDatabase.ConnectToDatabase(System.String,System.String@)~System.Boolean")]
[assembly: SuppressMessage("CodeQuality", "IDE0051:Remove unused private members", Justification = "<Pending>", Scope = "member", Target = "~M:BurnSoft.Database.MSSQL.MssqlDatabase.ErrorMessage(System.String,System.ArgumentNullException)~System.String")]
[assembly: SuppressMessage("CodeQuality", "IDE0051:Remove unused private members", Justification = "<Pending>", Scope = "member", Target = "~M:BurnSoft.Database.MSSQL.MssqlDatabase.ErrorMessage(System.String,System.InvalidCastException)~System.String")]
[assembly: SuppressMessage("Style", "IDE0059:Unnecessary assignment of a value", Justification = "<Pending>", Scope = "member", Target = "~M:BurnSoft.Database.MSSQL.MssqlDatabase.RunExec(System.String,System.String,System.String@)~System.Boolean")]
[assembly: SuppressMessage("CodeQuality", "IDE0051:Remove unused private members", Justification = "<Pending>", Scope = "member", Target = "~M:BurnSoft.Database.MySQL.MySqlDatabase.ErrorMessage(System.String,System.Exception)~System.String")]
[assembly: SuppressMessage("CodeQuality", "IDE0051:Remove unused private members", Justification = "<Pending>", Scope = "member", Target = "~M:BurnSoft.Database.MySQL.MySqlDatabase.ErrorMessage(System.String,System.InvalidCastException)~System.String")]
[assembly: SuppressMessage("Style", "IDE0059:Unnecessary assignment of a value", Justification = "<Pending>", Scope = "member", Target = "~M:BurnSoft.Database.MySQL.MySqlDatabase.RunQuery(System.String,System.String,System.String@)~System.Boolean")]
[assembly: SuppressMessage("Style", "IDE0059:Unnecessary assignment of a value", Justification = "<Pending>", Scope = "member", Target = "~M:BurnSoft.Database.SQLite.BaseDatabase.CreateDatabaseVersion(System.String,System.String@,System.Double)~System.Boolean")]
[assembly: SuppressMessage("Style", "IDE0059:Unnecessary assignment of a value", Justification = "<Pending>", Scope = "member", Target = "~M:BurnSoft.Database.SQLite.BaseDatabase.DbVersionExists(System.String,System.Double,System.String@)~System.Boolean")]
[assembly: SuppressMessage("CodeQuality", "IDE0051:Remove unused private members", Justification = "<Pending>", Scope = "member", Target = "~M:BurnSoft.Database.SQLite.BaseDatabase.ErrorMessage(System.String,System.ArgumentNullException)~System.String")]
[assembly: SuppressMessage("CodeQuality", "IDE0051:Remove unused private members", Justification = "<Pending>", Scope = "member", Target = "~M:BurnSoft.Database.SQLite.BaseDatabase.ErrorMessage(System.String,System.InvalidCastException)~System.String")]
[assembly: SuppressMessage("Style", "IDE0059:Unnecessary assignment of a value", Justification = "<Pending>", Scope = "member", Target = "~M:BurnSoft.Database.SQLite.BaseDatabase.GetDatabaseVersion(System.String,System.String@)~System.Double")]
[assembly: SuppressMessage("Style", "IDE0059:Unnecessary assignment of a value", Justification = "<Pending>", Scope = "member", Target = "~M:BurnSoft.Database.SQLite.BaseDatabase.UpdateDbVersion(System.String,System.Double,System.String@)~System.Boolean")]
[assembly: SuppressMessage("Style", "IDE0059:Unnecessary assignment of a value", Justification = "<Pending>", Scope = "member", Target = "~M:BurnSoft.Database.SQLite.SqLiteDataManagement.CleanDb(System.String,System.String@)~System.Boolean")]
[assembly: SuppressMessage("CodeQuality", "IDE0051:Remove unused private members", Justification = "<Pending>", Scope = "member", Target = "~M:BurnSoft.Database.SQLite.SqLiteDataManagement.ErrorMessage(System.String,System.ArgumentNullException)~System.String")]
[assembly: SuppressMessage("CodeQuality", "IDE0051:Remove unused private members", Justification = "<Pending>", Scope = "member", Target = "~M:BurnSoft.Database.SQLite.SqLiteDataManagement.ErrorMessage(System.String,System.InvalidCastException)~System.String")]
[assembly: SuppressMessage("Style", "IDE0059:Unnecessary assignment of a value", Justification = "<Pending>", Scope = "member", Target = "~M:BurnSoft.Database.SQLite.SqLiteDataManagement.GetDataBySql(System.String,System.String,System.String@)~System.Data.DataTable")]
[assembly: SuppressMessage("Style", "IDE0059:Unnecessary assignment of a value", Justification = "<Pending>", Scope = "member", Target = "~M:BurnSoft.Database.SQLite.SqLiteDataManagement.GetSingleValue(System.String,System.String,System.String,System.String,System.String@)~System.String")]
[assembly: SuppressMessage("Style", "IDE0059:Unnecessary assignment of a value", Justification = "<Pending>", Scope = "member", Target = "~M:BurnSoft.Database.SQLite.SqLiteDataManagement.GetSingleValueFromDatabase(System.String,System.String,System.String,System.Double,System.String@)~System.Double")]
[assembly: SuppressMessage("Style", "IDE0059:Unnecessary assignment of a value", Justification = "<Pending>", Scope = "member", Target = "~M:BurnSoft.Database.SQLite.SqLiteDataManagement.GetSingleValueFromDatabase(System.String,System.String,System.String,System.Int32,System.String@)~System.Int32")]
[assembly: SuppressMessage("Style", "IDE0059:Unnecessary assignment of a value", Justification = "<Pending>", Scope = "member", Target = "~M:BurnSoft.Database.SQLite.SqLiteDataManagement.GetSingleValueFromDatabase(System.String,System.String,System.String,System.String,System.String@)~System.String")]
[assembly: SuppressMessage("Style", "IDE0059:Unnecessary assignment of a value", Justification = "<Pending>", Scope = "member", Target = "~M:BurnSoft.Database.SQLite.SqLiteDataManagement.HasData(System.String,System.String,System.String@)~System.Boolean")]
[assembly: SuppressMessage("Style", "IDE0059:Unnecessary assignment of a value", Justification = "<Pending>", Scope = "member", Target = "~M:BurnSoft.Database.SQLite.SqLiteDataManagement.RunQuery(System.String,System.String,System.String@)~System.Boolean")]
